# Generated by Django 2.2 on 2019-04-12 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('title', models.CharField(max_length=250)),
                ('picture', models.CharField(max_length=400)),
                ('content', models.CharField(max_length=1000)),
                ('site_url', models.CharField(max_length=400)),
                ('vote_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('content', models.CharField(max_length=400)),
                ('vote_total', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='message_app.Post')),
            ],
        ),
    ]
